export function packageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      packageManager: "pnpm@9.15.0",
      type: "module",
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        test: "vitest run --reporter=json",
        "test:e2e": "playwright test --reporter=json",
        lint: "eslint .",
      },
      dependencies: {
        next: "15.5.20",
        react: "19.2.7",
        "react-dom": "19.2.7",
        "@react-three/fiber": "9.6.1",
        "@react-three/drei": "10.7.7",
        three: "0.185.1",
        gsap: "3.15.0",
        "@gsap/react": "2.1.2",
        lenis: "1.3.25",
        "react-error-boundary": "5.0.0",
        zustand: "5.0.3",
        zod: "4.4.3",
      },
      devDependencies: {
        "@axiom/cli": "file:./packages/axiom-cli",
        "@types/node": "22.10.5",
        "@types/react": "19.2.17",
        "@types/react-dom": "19.2.3",
        "@types/three": "0.185.1",
        "@playwright/test": "1.61.1",
        "axe-core": "4.10.2",
        "@axe-core/playwright": "4.10.1",
        eslint: "9.17.0",
        "@eslint/js": "9.17.0",
        "typescript-eslint": "8.19.0",
        "eslint-config-next": "15.5.20",
        "eslint-plugin-axiom": "file:./packages/eslint-plugin-axiom",
        typescript: "5.9.3",
        vitest: "4.1.10",
        "@testing-library/react": "16.3.2",
        "@testing-library/dom": "10.4.0",
        "happy-dom": "20.10.6",
        tailwindcss: "4.3.2",
        "raw-loader": "4.0.2",
      },
    },
    null,
    2,
  );
}
