import { DirectionJson } from "@/cli/schemas/direction.js";
import { BriefJson } from "@/cli/schemas/brief.js";

export function sampleDirection(candidate: string): DirectionJson {
  return {
    directionId: `dir_${candidate}`,
    thesis: `Sample direction ${candidate} — generated by atl direct generate.`,
    typography: {
      display: { family: "InterVariable", axis: { wght: [200, 800] }, case: "mixed" },
      text: { family: "InterVariable" },
      scaleRatio: 1.333,
    },
    color: {
      story: "Dark surface, light text.",
      tokensDraft: {
        "bg-primary": "#0B0F19",
        "text-primary": "#F5F7FA",
      },
    },
    space: { language: "airy", density: 0.3, gridBias: "asymmetric" },
    motionPersonality: { adjectives: ["calm"], tempo: "mid", playfulness: 0.2 },
    texture: { grain: 0.05, noiseShader: false },
    webglLevel: 0,
    sceneIdeas: ["Hero: large display type over dark field"],
  };
}

export function bespokeDirection(candidate: string, brief: BriefJson): DirectionJson {
  const brand = brief.brand.name;
  const mood = brief.mood.words.join(", ");
  const anti = brief.mood.antiWords.join(", ");
  const tempo = brief.webglAppetite >= 2 ? "fast" : brief.webglAppetite === 0 ? "slow" : "mid";
  return {
    directionId: `dir_${candidate}`,
    thesis: `Bespoke direction ${candidate} for ${brand}: ${mood}; avoiding ${anti}.`,
    typography: {
      display: { family: "InterVariable", axis: { wght: [200, 800] }, case: "mixed" },
      text: { family: "InterVariable" },
      scaleRatio: 1.333,
    },
    color: {
      story: `Color world tuned to ${mood}, deliberately excluding ${anti}.`,
      tokensDraft: {
        "bg-primary": "#0B0F19",
        "text-primary": "#F5F7FA",
      },
    },
    space: { language: "airy", density: 0.3, gridBias: "asymmetric" },
    motionPersonality: { adjectives: ["calm"], tempo, playfulness: 0.2 },
    texture: { grain: 0.05, noiseShader: brief.webglAppetite >= 1 },
    webglLevel: brief.webglAppetite,
    sceneIdeas: [
      `Hero concept for ${brief.goal.primary} aligned with ${mood}`,
      `Anti-pattern guard: no visuals evoking ${anti}`,
    ],
  };
}
