import type { RouteEntry } from "@/cli/schemas/agent-context.js";
import { safePath } from "@/cli/commands/plan-helpers.js";

export function routeTsx(path: string, componentName: string): string {
  const safe = safePath(path);
  return `// src/routes/${safe}.tsx — AXIOM MACHINE ZONE
// Route wrapper for ${path}; default export allowed (I-04 exception).
import { ${componentName} } from "@/components/${componentName}";

export default function ${componentName}Route() {
  return <${componentName} />;
}
`;
}

export function routeManifestTs(routes: RouteEntry[]): string {
  const imports = routes
    .map((r) => {
      const safe = safePath(r.path);
      return `import ${r.component}Route from "@/routes/${safe}.route";`;
    })
    .join("\n");
  const items = routes.map((r) => `  { path: "${r.path}", component: <${r.component}Route /> }`).join(",\n");
  return `// src/generated/route-manifest.tsx — AXIOM MACHINE ZONE
// Generated by axm add route / axm tokens build. Do not edit.
import type { ReactNode } from "react";
${imports}

export interface Route {
  path: string;
  component: ReactNode;
}

export const routes: Route[] = [
${items}
];
`;
}
